PROJECT = rabbitmq_prelaunch
PROJECT_DESCRIPTION = RabbitMQ prelaunch procedure
PROJECT_VERSION = 0.1.0

LOCAL_DEPS = mnesia
DEPS = rabbit_common

include ../../rabbitmq-components.mk
include ../../erlang.mk
